# Generated by Django 2.2.11 on 2020-05-04 19:56

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=64)),
                ('year', models.SmallIntegerField(blank=True)),
                ('category', models.IntegerField(choices=[(1, 'Horror'), (2, 'Kryminał'), (3, 'Sensacja'), (4, 'Romans'), (5, 'Biografia'), (6, 'Obyczaj'), (7, 'Muzyczny'), (8, 'Dokument i literatura faktu'), (9, 'Bajki dla dzieci'), (10, 'Sport i aktywnośc fizyczna'), (11, 'Podręcznik'), (12, 'Historyczno-przyrodnicza'), (13, 'Filozofia i nauki  scisłe'), (14, 'Atlasy i tablice naukowe'), (15, 'Prasa')], default=2)),
                ('description', models.TextField(blank=True)),
                ('isbn', isbn_field.fields.ISBNField(blank=True, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('dirty_isbn', isbn_field.fields.ISBNField(clean_isbn=False, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('available', models.IntegerField(choices=[(1, 'Tak'), (2, 'Nie')], default=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_biblioteczny.Author')),
            ],
        ),
    ]
